<a href="https://colab.research.google.com/github/luizevans/luizevans/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Verificando Versão

In [1]:
!python -V

Python 3.7.15


# Trabalhando com arrays Numpy

In [105]:
import numpy as np

In [ ]:
km = np.loadtxt('carros-km.txt')
km

In [ ]:
ano_fabric = np.loadtxt('carros-anos.txt', dtype = int)
ano_fabric

In [ ]:
km_media = km / (2022 - ano_fabric)
km_media

In [ ]:
type(km_media)

# A variavel _

In [14]:
5 * 2

10

In [15]:
_ + 3 * 2

16

In [16]:
_ / 3

5.333333333333333

In [18]:
10 % 2 + 3 // 10

0

In [24]:
2 ** 3 * 4

32

In [23]:
5 * (2 + 3) / 2


12.5

# Declaração de Variáveis

In [ ]:
ano_atual = 2019

In [25]:
text = 'A quilometragem média do veículo é '
Km = 100000
Ano_atual = 2019
Ano_fabricacao = 1999

# Listas

In [ ]:
Acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
Acessorios

In [30]:
Carro_1 = ['Jetta Variant', 'Motor 4.0 Turbo', 2003, 44410.0, False, ['Rodas de liga', 'Travas elétricas', 'Piloto automático'], 88078.64]
Carro_2 = ['Passat', 'Motor Diesel', 1991, 5712.0, False, ['Central multimídia', 'Teto panorâmico', 'Freios ABS'], 106161.94]

In [ ]:
carros = [Carro_1, Carro_2]
carros

In [41]:
# percorrer a lista
carros[0][-2][0]

'Rodas de liga'

# Métodos de Listas

In [42]:
Acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']


In [ ]:
# Ordena a lista
Acessorios.sort()
Acessorios

In [ ]:
# Adiciona 'X' no final da lista
Acessorios.append('Add')
Acessorios

In [54]:
# Remove o último item da lista
Acessorios.pop()
Acessorios
Acessorios.pop(0)
Acessorios

[]

In [56]:
Acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [59]:
Acessorios_2 = Acessorios.copy()
Acessorios_2

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [60]:
Acessorios.pop()

'Sensor de chuva'

In [120]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Central multimídia',
 'Teto panorâmico',
 'Freios ABS',
 '4 X 4',
 'Painel digital',
 'Piloto automático',
 'Bancos de couro',
 'Câmera de estacionamento',
 'Piloto automático',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Freios ABS',
 'Câmbio automático',
 'Bancos de couro',
 'Central multimídia',
 'Vidros elétricos']

In [62]:
Acessorios_2

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

# Estrutura de Repetição e Condicionais

For

In [ ]:
for item in Acessorios:
  print(item)

range()

In [ ]:
list(range(10))

In [ ]:
for i in range(10):
  print(i ** 2)

Armazenar em uma lista

In [66]:
quadrado = []
for i in range(10):
  quadrado.append(i ** 2)
quadrado

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [67]:
# Forma direta de jogar os valores direto na lista com o FOR
[i ** 2 for i in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

Loop Aninhados

In [68]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [ ]:
for item in dados:
  print(item)

In [ ]:
for lista in dados:
  for item in lista:
    print(item)

In [ ]:
Acessorios = []
for lista in dados:
  for item in lista:
    Acessorios.append(item)
Acessorios

Utilizando o set()

In [ ]:
# Elimina duplicata
list(set(Acessorios))

List Comprehensions

In [75]:
[item for lista in dados for item in lista]

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Central multimídia',
 'Teto panorâmico',
 'Freios ABS',
 '4 X 4',
 'Painel digital',
 'Piloto automático',
 'Bancos de couro',
 'Câmera de estacionamento',
 'Piloto automático',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Freios ABS',
 'Câmbio automático',
 'Bancos de couro',
 'Central multimídia',
 'Vidros elétricos']

In [76]:
list(set([item for lista in dados for item in lista]))

['Travas elétricas',
 'Teto panorâmico',
 'Ar condicionado',
 '4 X 4',
 'Freios ABS',
 'Vidros elétricos',
 'Bancos de couro',
 'Controle de estabilidade',
 'Piloto automático',
 'Painel digital',
 'Sensor de estacionamento',
 'Câmera de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Rodas de liga',
 'Central multimídia',
 'Câmbio automático']

if/else

In [ ]:
# 1º item da lista - Nome do veículo
# 2º item da lista - Ano de fabricação
# 3º item da lista - Veículo é zero km?

dados = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False]
]
dados

In [79]:
for lista in dados:
  print(lista[2])

False
False
False
True
False
False
True
False
False
False


In [ ]:
for lista in dados:
  if (lista[2] == False):
    print(lista)


In [83]:
zero_km_Y = []
for lista in dados:
  if (lista[2] == True):
    zero_km_Y.append(lista)
zero_km_Y

[['DS5', 2019, True], ['A5', 2019, True]]

In [ ]:
zero_km_N = []
for lista in dados:
  if (lista[2] == False):
    zero_km_N.append(lista)
zero_km_N

In [ ]:
# Lista Comprehensions
[lista for lista in dados if lista[2] == False ]

Instruções if-else, if, elif e else

In [92]:
# 1º item da lista - Nome do veículo
# 2º item da lista - Ano de fabricação
# 3º item da lista - Veículo é zero km?

dados = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False]]

In [93]:
zero_km_Y, zero_km_N = [], []
for lista in dados:
  if (lista[2] == True):
    zero_km_Y.append(lista)
  else:
    zero_km_N.append(lista)



In [94]:
zero_km_Y


[['DS5', 2019, True], ['A5', 2019, True]]

In [95]:
zero_km_N

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [101]:
A, B, C = [], [], []
for lista in dados:
  if (lista[1] <= 2000):
    A.append(lista)
  elif(2000 < lista[1] <= 2010):
    B.append(lista)
  else:
    C.append(lista)

In [102]:
A

[['Passat', 1991, False], ['Crossfox', 1990, False]]

In [103]:
B

[['Jetta Variant', 2003, False],
 ['Aston Martin DB4', 2006, False],
 ['Série 3 Cabrio', 2009, False]]

In [104]:
C

[['DS5', 2019, True],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

Importando Numpay

In [108]:
import numpy as np

In [109]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Importando apenas o 'arenge'

In [111]:
from numpy import arange

Apartir de uma lista

In [112]:
km = np.array([100, 2500, 4350, 30])
km

array([ 100, 2500, 4350,   30])

Apartir de dados externos

In [ ]:
km = np.loadtxt(fname = 'carros-km.txt', dtype = int)
km

In [127]:
Acessorios = np.array(dados)

In [128]:
Acessorios

array([['Jetta Variant', '2003', 'False'],
       ['Passat', '1991', 'False'],
       ['Crossfox', '1990', 'False'],
       ['DS5', '2019', 'True'],
       ['Aston Martin DB4', '2006', 'False'],
       ['Palio Weekend', '2012', 'False'],
       ['A5', '2019', 'True'],
       ['Série 3 Cabrio', '2009', 'False'],
       ['Dodge Jorney', '2019', 'False'],
       ['Carens', '2011', 'False']], dtype='<U21')

In [129]:
Acessorios.shape

(10, 3)

Comparando desempenho com lista

In [130]:
np_array = np.arange(10000)

In [131]:
py_list = list(range(10000))

In [134]:
# Performance do código construido
%time for _ in range(100): np_array *= 2

CPU times: user 1.67 ms, sys: 0 ns, total: 1.67 ms
Wall time: 1.67 ms


In [135]:
%time for _ in range(100): py_list = [x * 2 for x in py_list]

CPU times: user 61.4 ms, sys: 1.28 ms, total: 62.7 ms
Wall time: 62.6 ms


Operações aritméticas com arrays Numpy

In [136]:
km = [44410., 5712., 37123., 0., 25757.]
anos = [2003, 1991, 1990, 2019, 2006]

In [ ]:
# idade = 2022 - anos

In [138]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])

In [139]:
idade = 2022 - anos


In [140]:
idade

array([19, 31, 32,  3, 16])

Operação entra dois arrays

In [141]:
km_media = km / idade

In [142]:
km_media

array([2337.36842105,  184.25806452, 1160.09375   ,    0.        ,
       1609.8125    ])

Operações com arrays de duas dimensões

In [143]:
dados = np.array([km, anos])

In [144]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [145]:
dados.shape

(2, 5)

Seleções de Arrays NUmpy

In [146]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [147]:
dados[1]

array([2003., 1991., 1990., 2019., 2006.])

In [148]:
km_media = dados[0] / (2022 - dados[1])

In [149]:
km_media

array([2337.36842105,  184.25806452, 1160.09375   ,    0.        ,
       1609.8125    ])

# Desafio Alura 01 : Considerando o enunciado acima, verifique cada alternativa e assinale as que calculam corretamente o IMC, não apresentando erro(s) durante o seu cálculo.

In [154]:
peso = np.array([106.0, 68.5, 75.0])
altura = np.array([1.9, 1.53, 1.75])
IMC = peso / altura ** 2
IMC

array([29.36288089, 29.26224956, 24.48979592])

# Indexação

In [156]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [158]:
contador[0]

0

In [160]:
item = 6
index = item - 1
contador[index]

5

In [162]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [163]:
dados[1]

array([2003., 1991., 1990., 2019., 2006.])

In [164]:
dados[1, 2]

1990.0

In [166]:
dados[0,2]

37123.0

In [167]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [168]:
contador[1:4]

array([1, 2, 3])

In [170]:
# Passo de 2 em 2(impares)
contador[1:8:2]

array([1, 3, 5, 7])

In [171]:
# Passo 2 em 2 (pares)
contador[::2]

array([0, 2, 4, 6, 8])

In [172]:
# Pegar linhas e colunas selecionadas
dados[:, 1:4] 

array([[ 5712., 37123.,     0.],
       [ 1991.,  1990.,  2019.]])

In [173]:
# Pegar linhas e colunas selecionadas
dados[:, 1:3] 

array([[ 5712., 37123.],
       [ 1991.,  1990.]])

In [175]:
# Pegar algumas linhas da coluna
dados[:, 1:3][1]

array([1991., 1990.])

In [178]:
# Operações entres linhas
dados[:, 1:3][0] / (2022 - dados[:, 1:3][1])

array([ 184.25806452, 1160.09375   ])

In [179]:
contador[contador > 5]

array([6, 7, 8, 9])

In [180]:
dados[1] > 2000

array([ True, False, False,  True,  True])

In [181]:
dados[:, dados[1] > 2000]

array([[44410.,     0., 25757.],
       [ 2003.,  2019.,  2006.]])

# Desafio Alura 02 : Marque a alternativa que mostra o código que permite a seleção, sem utilização de operadores lógicos (and e or), das informações de nome e estado civil, somente das pessoas do sexo masculino.

In [182]:
dados = np.array(
    [
        ['Roberto', 'casado', 'masculino'],
        ['Sheila', 'solteira', 'feminino'],
        ['Bruno', 'solteiro', 'masculino'],
        ['Rita', 'casada', 'feminino']
    ]
)

In [183]:
dados[0::2, :2]

array([['Roberto', 'casado'],
       ['Bruno', 'solteiro']], dtype='<U9')

# Atribulos Numpy

ndarray.shape

In [185]:
dados = np.array([[44410.,  5712., 37123.,     0., 25757.], [ 2003.,  1991.,  1990.,  2019.,  2006.]])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [186]:
dados.shape

(2, 5)

ndarray.ndim

In [187]:
dados.ndim

2

ndarray.size

In [188]:
dados.size

10

ndarrya.dtype

In [189]:
dados.dtype

dtype('float64')

ndarray.T

In [191]:
# Converte linhas em colunas
dados.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

# Métodos

In [193]:
# tolist()
dados.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

In [194]:
# ndarray.reshape(shape[, order])
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [195]:
contador.reshape((5, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [196]:
contador.reshape((5, 2), order='F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [200]:
km = [44410, 5712, 37123, 0, 25757]
anos = [2003, 1991, 1990, 2019, 2006]

In [201]:
info_carros = km + anos

In [202]:
info_carros

[44410, 5712, 37123, 0, 25757, 2003, 1991, 1990, 2019, 2006]

In [208]:
np.array(info_carros).reshape((2, 5))

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [206]:
np.array(info_carros).reshape((5, 2), order="F")

array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

In [210]:
# ndarray.resize()
dados_new = dados.copy()
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [213]:
dados_new.resize((3, 5), refcheck=False)
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [214]:
dados_new[2] = dados_new[0] / (2022 - dados_new[1])
dados_new

array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2019.        ,
         2006.        ],
       [ 2337.36842105,   184.25806452,  1160.09375   ,     0.        ,
         1609.8125    ]])

In [218]:
dados_new.reshape((5, 3))

array([[44410.        ,  5712.        , 37123.        ],
       [    0.        , 25757.        ,  2003.        ],
       [ 1991.        ,  1990.        ,  2019.        ],
       [ 2006.        ,  2337.36842105,   184.25806452],
       [ 1160.09375   ,     0.        ,  1609.8125    ]])

# Estatísticas com arrays Numpy

In [220]:
anos = np.loadtxt(fname = "carros-anos.txt", dtype = int)
km = np.loadtxt(fname = "carros-km.txt")
valor = np.loadtxt(fname = "carros-valor.txt")

In [221]:
anos.shape

(258,)

In [ ]:
dataset = np.column_stack((anos, km, valor))
dataset

In [223]:
dataset.shape

(258, 3)

In [227]:
# np.mean() - Calculando a média
np.mean(dataset, axis = 0) # axis = 0 (média por coluna)

array([ 2007.51162791, 44499.41472868, 98960.51310078])

# nd.mean()

Retorna a média dos elementos do arrays

In [ ]:
# np.mean() - Calculando a média
np.mean(dataset, axis = 1) # axis = 1 (média por linhas)

In [230]:
# Selecionando um coluna
np.mean(dataset[:,1], axis = 0)

44499.41472868217

In [231]:
# Selecionando um coluna
np.mean(dataset[:, 2], axis = 0)

98960.51310077519

# np.std()

Retorna o desvio padrão dos elemtnso do array ao longo do eixo especificado.

In [232]:
np.std(dataset[:, 2])

29754.101150388564

# nparray.sum()

Retorna a soma dos elementos do array ao longo do eixo especificado.[texto do link](https://)

In [234]:
dataset[:, 1].sum()

11480849.0

# np.sum()

Retorna a soma dos elementos do array ao longo do eixo especificado.

In [236]:
np.sum(dataset, axis = 0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [237]:
np.sum(dataset[:, 2])

25531812.38